### PR TITLE
 ICS generation Multiple Events

### PR DESCRIPTION
**Pull request by svnindia**
support for multiple VEVENT in VCALENDAR #33 
pass the event as array events = [{}]  

To try the fixes : npm install --save https://github.com/svnindia/ics

### CODE REVIEW

**Comment by StevenACoffman** [comment]
@svnindia Ooo! Nice functionality! I wonder if those commented tests could be fixed to pass?

**Comment by JackAdams** [comment]
This is awesome and I'd love to see it merged.  Is the API backwards-compatible though?  I see some of the original tests have been changed to accommodate the presence of a `productId` in the arguments to some functions.  e.g. What if someone has existing code where the second argument for `createEvent` is a callback, rather than a `productId` string?

**Comment by joariasl** [comment]
@svnindia The `PRODID` (`productId` param) is not a required param in one ical.
I recomed change the method for receive:
`createEvent([attributes], {params}, [callback])`

and validate if the specific params are undefined, don't add these to the ical output.

**Comment by joariasl** [comment]
I sent a new pull request for you @svnindia, with my improvements and support for previous version. With a `createEvent` and a `createCalendar` methods.
You can see it in: [joariasl/ics](/joariasl/ics)
And for try it: `npm install --save https://github.com/joariasl/ics`

**Comment by janaleible** [comment]
This is what I love about github -- the moment I realise the library cannot yet do what I need there's already people working on the solution :) 
One little thing though -- if no `uid` attribute is given for the events in the array given to `createCalendar()`, they all end up with the same `uid`. This confuses e.g. the google calendar, for me it only imported one of the events in the resulting `.ics`  file.

**Comment by adamgibbons** [comment]
Thanks for all this! Taking a look now. As @janaleible mentioned, the `uid` issue needs to be addressed.

**Comment by joariasl** [comment]
I grouped and resolved the conflicts in the pull request #47

**Pull request closed without merging**
