### PR TITLE
Support for customer ProdId, Start and End Time UTC fixes.

### PR DESCRIPTION
**Pull request by alexleventer**
- Add support for custom ProdId.
- Fix issues with Start and End time when providing an absolute UTC time.
- Update Chai, Moment and UUID.

### CODE REVIEW

**Comment by alexleventer** [comment]
FYI @adamgibbons 52930c29e9f671088019ec70ca8260efbb40c9e3 introduced a bug that this PR fixes.

**Comment by adamgibbons** [comment]
@alexleventer got it, thanks. can you get the tests passing? happy to merge after that.

**Comment by mhewett** [comment]
@alexleventer Line 127 of your modified ics.js should have isUTC(startString), not isUTC(string).

**Comment by mhewett** [comment]
@alexleventer Also the break; at line 239 after the return is unreachable and therefore unnecessary.  Both of these errors were found by WebStorm.

**Comment by mhewett** [comment]
@alexleventer And finally, formatDTEND Form #2 (UTC) should use moment.utc(), not moment() and should append a 'Z' on the end.   Then the module finally works correctly if both start time and end time are ISO-8601 UTC timestamps.

**Pull request closed without merging**
