### PR TITLE
Add the partstat option in attendees

### PR DESCRIPTION
**Pull request by m-vinc**
I need to add a list of attendees with the partstat attribute, so i add it and I think this can be useful for others, tell me if i've made a mistake :)

### CODE REVIEW

**Comment by adamgibbons** [comment]
@m-vinc this looks great and is definitely useful. Can you add a test for this and update the README so people know this exists?

**Comment by m-vinc** [comment]
Hey, when i try to run tests, setDateWithUTCtime failed, so i try to understand the test and i see you subtract the offset when the sign is negative. but if you want to get utc datetime from local you need to subract when the offset is positive no ?

**Comment by jcaron23** [comment]
While you have your hands in there, it could make sense to add [ROLE](https://tools.ietf.org/html/rfc5545#section-3.2.16) as well?

**Comment by m-vinc** [comment]
It seems useful too, i’ll try to add it tomorrow !

**Comment by adamgibbons** [comment]
@m-vinc thank you!

**Pull request merged**
