### PR TITLE
Add a timezone parameter to specify the timezone of DTSTART and DTEND

### PR DESCRIPTION
**Pull request by m-vinc**
Hi,
I add a timezone parameter which set the TZID to event DTSTART and DTEND to avoid bad date with the local startType (which is not documented ?).

### CODE REVIEW

**Comment by jcaron23** [comment]
Note that per [RFC5545 section 3.2.19](https://tools.ietf.org/html/rfc5545#section-3.2.19),

> An individual "VTIMEZONE" calendar component MUST be specified for each unique "TZID" parameter value specified in the iCalendar object.

So adding a TZID is one thing, but the result is not compliant unless you also add the corresponding `VTIMEZONE` entry, which is quite a complex beast.

**Comment by adamgibbons** [comment]
I'd love to address `VTIMEZONE` but I don't have the bandwidth. If you'd like to add this functionality it's certainly welcome.

**Comment by m-vinc** [comment]
I do not have a lot of time right now, but when i can, I'll try to find a solution to add a corresponding VTIMEZONE if you specify a tzid.

**Comment by TiE23** [comment]
I did not grasp the size of this problem until I exported from Calendar.app a simple calendar that repeats a 9am meeting on Mondays in `America/New_York`.


(Indents and blank lines added by me for clarity)
```
BEGIN:VCALENDAR
	CALSCALE:GREGORIAN
	PRODID:-//Apple Inc.//macOS 13.3.1//EN
	VERSION:2.0
	X-APPLE-CALENDAR-COLOR:#FF9500
	X-WR-CALNAME:Exported from MacOS Calendar

	BEGIN:VTIMEZONE
		TZID:America/New_York

		BEGIN:DAYLIGHT
			DTSTART:20070311T020000
			RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
			TZNAME:EDT
			TZOFFSETFROM:-0500
			TZOFFSETTO:-0400
		END:DAYLIGHT

		BEGIN:STANDARD
			DTSTART:20071104T020000
			RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
			TZNAME:EST
			TZOFFSETFROM:-0400
			TZOFFSETTO:-0500
		END:STANDARD
	END:VTIMEZONE

	BEGIN:VEVENT
		CREATED:20230713T200245Z
		DTEND;TZID=America/New_York:20230626T093000
		DTSTAMP:20230713T200258Z
		DTSTART;TZID=America/New_York:20230626T090000
		LAST-MODIFIED:20230713T200245Z
		RRULE:FREQ=WEEKLY
		SEQUENCE:0
		SUMMARY:Repeat on Mondays
		TRANSP:OPAQUE
		UID:C4B3C83C-E77E-4DD8-B28A-6D76F6EAFACD
	END:VEVENT

END:VCALENDAR
```

If this is to be believed... one needs to basically reverse engineer daylight savings rules for the entire world?

I just realized with horror that my in-house calendar export system is not respecting daylight savings, nearly a year since deploying it, and my heart is sinking realizing that there appears to be no "quick" fix. Insane.

**Pull request closed without merging**
