### PR TITLE
Better handling of all day events

### PR DESCRIPTION
**Pull request by thespooler**
According to https://tools.ietf.org/html/rfc5545#section-3.6.1, 

> The "VEVENT" is also the calendar component used to specify an
    anniversary or daily reminder within a calendar.  These events
    have a DATE value type for the "DTSTART" property instead of the
    default value type of DATE-TIME.  If such a "VEVENT" has a "DTEND"
    property, it MUST be specified as a DATE value also.

### CODE REVIEW

**Comment by adamgibbons** [comment]
Thanks for this. The PR has a few tests failing - can you address those? https://travis-ci.org/adamgibbons/ics/builds/355046156?utm_source=github_status&utm_medium=notification

**Comment by thespooler** [comment]
Done. All good now. I event threw in some basic tests for all day events.
Could perhaps be improved by checking how the long/short forms should interact in opposing starts-ends. I just don't know how it should be.

**Comment by leodutra** [comment]
Bump!

**Comment by adamgibbons** [comment]
Thanks @thespooler this is next up on my list - will review/merge this weekend.

**Comment by adamgibbons** [comment]
👍 this looks good - will you resolve the merge conflict and then I'll merge this asap.

**Comment by thespooler** [comment]
@adamgibbons Merge resolved.

**Pull request merged**
