### PR TITLE
Allow DIR attribute into organizer and attendees

### PR DESCRIPTION
**Pull request by ibc**
This PR adds [DIR](https://www.kanzaki.com/docs/ical/dir.html) attribute into `organizer` and `attendees` (related to #86).

### CODE REVIEW

**Comment by adamgibbons** [comment]
@ibc great work, thanks!

**Comment by adamgibbons** [comment]
@ibc If you have a chance, would you add this to the documentation? I won't hold up this PR for it, just make a new one when you're able.

**Comment by ibc** [comment]
I'll do next days. Thanks.

**Comment by ibc** [comment]
Done

**Comment by ibc** [comment]
mmm, forgot to document it in `notes.md`, doing it right now.

**Comment by ibc** [comment]
No, `notes.md` is not `ics` project documentation. So yes, done.

**Pull request merged**
